// Generated by tools/localize.mjs from public/assets/js/i18n.js.
export const LOCALES = {
  "en": {
    "path": "/",
    "lang": "en",
    "hreflang": "en"
  },
  "zh-cn": {
    "path": "/zh-cn/",
    "lang": "zh-CN",
    "hreflang": "zh-CN"
  },
  "zh-tw": {
    "path": "/zh-tw/",
    "lang": "zh-TW",
    "hreflang": "zh-TW"
  },
  "ja": {
    "path": "/ja/",
    "lang": "ja",
    "hreflang": "ja"
  },
  "ko": {
    "path": "/ko/",
    "lang": "ko",
    "hreflang": "ko"
  },
  "es": {
    "path": "/es/",
    "lang": "es",
    "hreflang": "es"
  },
  "fr": {
    "path": "/fr/",
    "lang": "fr",
    "hreflang": "fr"
  },
  "de": {
    "path": "/de/",
    "lang": "de",
    "hreflang": "de"
  },
  "pt-br": {
    "path": "/pt-br/",
    "lang": "pt-BR",
    "hreflang": "pt-BR"
  },
  "ru": {
    "path": "/ru/",
    "lang": "ru",
    "hreflang": "ru"
  },
  "hi": {
    "path": "/hi/",
    "lang": "hi",
    "hreflang": "hi"
  },
  "id": {
    "path": "/id/",
    "lang": "id",
    "hreflang": "id"
  },
  "vi": {
    "path": "/vi/",
    "lang": "vi",
    "hreflang": "vi"
  },
  "tr": {
    "path": "/tr/",
    "lang": "tr",
    "hreflang": "tr"
  },
  "it": {
    "path": "/it/",
    "lang": "it",
    "hreflang": "it"
  }
};
